# Generated by Django 5.1.15 on 2026-04-13 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('categoria', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Moda', 'Moda'), ('Alimentos', 'Alimentos'), ('Casa', 'Casa'), ('Beleza', 'Beleza'), ('Esportes', 'Esportes'), ('Outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('score_risco', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Score de Risco (0–10)')),
                ('nivel_risco', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MÉDIO', 'Médio'), ('ALTO', 'Alto'), ('CRÍTICO', 'Crítico')], max_length=10, null=True, verbose_name='Nível de Risco')),
                ('resumo_ia', models.TextField(blank=True, verbose_name='Resumo da IA')),
                ('scored_at', models.DateTimeField(blank=True, null=True, verbose_name='Último scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-score_risco', 'nome'],
            },
        ),
    ]
