# Generated by Django 5.1.15 on 2026-04-13 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=255, verbose_name='Produto')),
                ('preco_ofertado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Preço Ofertado')),
                ('preco_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço de Mercado (BigQuery)')),
                ('moeda', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dólar (USD)')], default='BRL', max_length=3)),
                ('data', models.DateField(verbose_name='Data da Cotação')),
                ('margem_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margem (%)')),
                ('fonte_bq', models.CharField(blank=True, help_text='Tabela/query usada para obter o preço de mercado', max_length=100, verbose_name='Fonte BigQuery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='suppliers.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
